version: "3.7"

services:
    mongo:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 27018:27017
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
