import { ENUM_PAGINATION_ORDER_DIRECTION_TYPE } from "./pagination.constants.enum";

export const PAGINATION_PER_PAGE = 10;
export const PAGINATION_MAX_PER_PAGE = 100;
export const PAGINATION_OFFSET = 0;
export const PAGINATION_PAGE = 1;
export const PAGINATION_MAX_PAGE = 20;
export const PAGINATION_ORDER_BY = "createdAt";
export const PAGINATION_ORDER_DIRECTION: ENUM_PAGINATION_ORDER_DIRECTION_TYPE =
    ENUM_PAGINATION_ORDER_DIRECTION_TYPE.ASC;
export const PAGINATION_AVAILABLE_ORDER_BY: string[] = ["createdAt"];
export const PAGINATION_AVAILABLE_ORDER_DIRECTION: ENUM_PAGINATION_ORDER_DIRECTION_TYPE[] =
    Object.values(ENUM_PAGINATION_ORDER_DIRECTION_TYPE);
